"""Conservative non-regression audit across potentially incompatible identities.

The official quality-gated artifact and the reconstructed trade universe may carry
``trade_id`` values generated by different pipelines. A zero-overlap set comparison
therefore cannot, by itself, prove that official trades disappeared. This module
separates artifact-level diagnostics from canonical non-regression authority and
fails closed whenever a shared, unique identity namespace cannot be demonstrated.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

import pandas as pd

from .eligibility import normalize_trade_id


def normalized_identity_values(frame: pd.DataFrame, column: str) -> list[str]:
    """Return non-empty normalized identity values without mutating ``frame``."""

    if column not in frame.columns:
        return []
    return [
        value
        for value in frame[column].map(normalize_trade_id).tolist()
        if value
    ]


def identity_set(frame: pd.DataFrame) -> set[str]:
    """Return the artifact ``trade_id`` set used for diagnostics and row display."""

    return set(normalized_identity_values(frame, "trade_id"))


def duplicate_identity_row_count(values: Iterable[str]) -> int:
    """Count rows participating in a duplicate normalized identity group."""

    materialized = list(values)
    if not materialized:
        return 0
    series = pd.Series(materialized, dtype="string")
    return int(series.duplicated(keep=False).sum())


def _diagnostic_set_comparison(
    official_values: list[str],
    universe_values: list[str],
) -> dict[str, Any]:
    official_ids = set(official_values)
    universe_ids = set(universe_values)
    overlap = official_ids & universe_ids
    return {
        "official_rows_with_identity": len(official_values),
        "universe_rows_with_identity": len(universe_values),
        "official_unique_keys": len(official_ids),
        "universe_unique_keys": len(universe_ids),
        "overlap_unique_keys": len(overlap),
        "official_keys_missing_from_universe": len(official_ids - universe_ids),
        "universe_keys_not_in_official": len(universe_ids - official_ids),
        "official_duplicate_rows": duplicate_identity_row_count(official_values),
        "universe_duplicate_rows": duplicate_identity_row_count(universe_values),
        "official_overlap_rate": (
            float(len(overlap) / len(official_ids)) if official_ids else 0.0
        ),
    }


def _canonical_unavailability_reasons(
    *,
    official_has_trade_id_column: bool,
    universe_has_trade_id_column: bool,
    official_unique_ids: int,
    universe_unique_ids: int,
    artifact_overlap: int,
    official_duplicate_rows: int,
    universe_duplicate_rows: int,
) -> list[str]:
    reasons: list[str] = []
    if not official_has_trade_id_column:
        reasons.append("official_trade_id_column_missing")
    if not universe_has_trade_id_column:
        reasons.append("universe_trade_id_column_missing")
    if official_unique_ids == 0:
        reasons.append("official_trade_id_population_empty")
    if universe_unique_ids == 0:
        reasons.append("universe_trade_id_population_empty")
    if official_unique_ids and universe_unique_ids and artifact_overlap == 0:
        reasons.append("artifact_trade_id_zero_overlap_namespace_unproven")
    if official_duplicate_rows:
        reasons.append("official_trade_id_not_unique")
    if universe_duplicate_rows:
        reasons.append("universe_trade_id_not_unique")
    return sorted(set(reasons))


def compare_official_projection(
    official: pd.DataFrame,
    row_projection: pd.DataFrame,
) -> dict[str, Any]:
    """Compare official and projected cohorts without overstating identity loss.

    ``trade_id`` receives canonical authority only when both artifacts expose a
    non-empty, unique namespace with at least one exact shared identity. ``order_id``
    is reported solely as diagnostic continuity evidence because its namespace and
    uniqueness are not guaranteed by these artifacts.
    """

    official_trade_values = normalized_identity_values(official, "trade_id")
    universe_trade_values = normalized_identity_values(row_projection, "trade_id")
    official_ids = set(official_trade_values)
    universe_ids = set(universe_trade_values)

    projected_ids = {
        normalize_trade_id(getattr(row, "trade_id", ""))
        for row in row_projection.itertuples(index=False)
        if bool(getattr(row, "eligible_for_model_training", False))
        and normalize_trade_id(getattr(row, "trade_id", ""))
    }

    retained = official_ids & projected_ids
    blocked_official = official_ids - projected_ids
    new_eligible = projected_ids - official_ids
    official_missing_from_universe = official_ids - universe_ids

    reasons_by_id: dict[str, list[str]] = {}
    for row in row_projection.itertuples(index=False):
        trade_id = normalize_trade_id(getattr(row, "trade_id", ""))
        if trade_id:
            reasons_by_id[trade_id] = list(getattr(row, "block_reasons", []))

    trade_diagnostic = _diagnostic_set_comparison(
        official_trade_values,
        universe_trade_values,
    )
    order_diagnostic = _diagnostic_set_comparison(
        normalized_identity_values(official, "order_id"),
        normalized_identity_values(row_projection, "order_id"),
    )

    artifact_namespace_compatible = bool(
        "trade_id" in official.columns
        and "trade_id" in row_projection.columns
        and trade_diagnostic["official_unique_keys"] > 0
        and trade_diagnostic["universe_unique_keys"] > 0
        and trade_diagnostic["overlap_unique_keys"] > 0
    )
    canonical_identity_computable = bool(
        artifact_namespace_compatible
        and trade_diagnostic["official_duplicate_rows"] == 0
        and trade_diagnostic["universe_duplicate_rows"] == 0
    )
    canonical_nonregression_evaluable = canonical_identity_computable

    unavailability_reasons = _canonical_unavailability_reasons(
        official_has_trade_id_column="trade_id" in official.columns,
        universe_has_trade_id_column="trade_id" in row_projection.columns,
        official_unique_ids=int(trade_diagnostic["official_unique_keys"]),
        universe_unique_ids=int(trade_diagnostic["universe_unique_keys"]),
        artifact_overlap=int(trade_diagnostic["overlap_unique_keys"]),
        official_duplicate_rows=int(trade_diagnostic["official_duplicate_rows"]),
        universe_duplicate_rows=int(trade_diagnostic["universe_duplicate_rows"]),
    )

    unexplained_removed: list[str] | None
    explained_removed: list[str] | None
    newly_blocked: list[str]
    official_identity_loss_proven = False
    official_identity_retention_proven = False

    if not canonical_nonregression_evaluable:
        status = "blocked"
        reason = "canonical_identity_unavailable_for_official_artifact"
        unexplained_removed = None
        explained_removed = None
        newly_blocked = sorted(universe_ids - official_ids - projected_ids)
    else:
        unexplained_removed = sorted(
            trade_id
            for trade_id in blocked_official
            if trade_id in universe_ids and not reasons_by_id.get(trade_id)
        )
        explained_removed = sorted(
            trade_id
            for trade_id in blocked_official
            if trade_id not in set(unexplained_removed)
        )
        newly_blocked = sorted(
            trade_id
            for trade_id in universe_ids - official_ids
            if trade_id not in projected_ids
        )

        if official_missing_from_universe or unexplained_removed:
            status = "blocked"
            reason = "unexplained_official_identity_loss"
            official_identity_loss_proven = True
        elif blocked_official:
            status = "review_required"
            reason = "explained_quality_or_temporal_reduction"
        else:
            status = "ok"
            reason = "all_official_ids_retained"
            official_identity_retention_proven = True

    return {
        "status": status,
        "reason": reason,
        "canonical_identity_source": (
            "artifact_trade_id" if canonical_nonregression_evaluable else None
        ),
        "canonical_identity_computable": canonical_identity_computable,
        "canonical_nonregression_evaluable": canonical_nonregression_evaluable,
        "canonical_identity_unavailability_reasons": unavailability_reasons,
        "official_identity_loss_proven": official_identity_loss_proven,
        "official_identity_retention_proven": official_identity_retention_proven,
        "artifact_trade_id_namespace_compatible": artifact_namespace_compatible,
        "artifact_trade_id_has_identity_authority": canonical_identity_computable,
        "artifact_trade_id_overlap_unique_keys": int(
            trade_diagnostic["overlap_unique_keys"]
        ),
        "artifact_trade_id_missing_official_keys": int(
            trade_diagnostic["official_keys_missing_from_universe"]
        ),
        "artifact_trade_id_official_duplicate_rows": int(
            trade_diagnostic["official_duplicate_rows"]
        ),
        "artifact_trade_id_universe_duplicate_rows": int(
            trade_diagnostic["universe_duplicate_rows"]
        ),
        "order_id_diagnostic_overlap_unique_keys": int(
            order_diagnostic["overlap_unique_keys"]
        ),
        "order_id_diagnostic_missing_official_keys": int(
            order_diagnostic["official_keys_missing_from_universe"]
        ),
        "order_id_diagnostic_official_duplicate_rows": int(
            order_diagnostic["official_duplicate_rows"]
        ),
        "order_id_diagnostic_universe_duplicate_rows": int(
            order_diagnostic["universe_duplicate_rows"]
        ),
        "order_id_has_identity_authority": False,
        "official_rows": int(len(official)),
        "official_unique_trade_ids": len(official_ids),
        "projected_rows": len(projected_ids),
        "universe_unique_trade_ids": len(universe_ids),
        "official_ids_retained": len(retained),
        "official_ids_blocked": len(blocked_official),
        "new_ids_eligible": len(new_eligible),
        "newly_blocked_ids": len(newly_blocked),
        "official_ids_missing_from_universe": len(official_missing_from_universe),
        "unexplained_removed_official_ids": (
            len(unexplained_removed) if unexplained_removed is not None else None
        ),
        "retained_official_ids": sorted(retained),
        "blocked_official_ids": sorted(blocked_official),
        "explained_removed_official_ids": explained_removed,
        "newly_eligible_ids": sorted(new_eligible),
        "newly_blocked_trade_ids": newly_blocked,
        "official_missing_from_universe_ids": sorted(
            official_missing_from_universe
        ),
        "unexplained_removed_official_trade_ids": unexplained_removed,
    }
