from __future__ import annotations

from .contracts import (
    DashboardCommandLevel,
    DashboardCommandRisk,
    DashboardCommandSideEffect,
)


N1_COMMANDS = (
    "REFRESH_VIEW", "FILTER_PERIOD", "SELECT_SYMBOL", "EXPORT_READONLY_REPORT",
    "OPEN_RUNBOOK", "COPY_SNAPSHOT_PATH", "VIEW_AUDIT_DETAILS",
    "VIEW_READINESS_DETAILS", "VIEW_DECISION_TRACE", "VIEW_DATASET_PIPELINE_STATUS",
)
N2_COMMANDS = (
    "PAUSE_PAPER_ENTRIES", "RESUME_PAPER_ENTRIES", "REQUEST_SNAPSHOT_REFRESH",
    "REQUEST_PAPER_FEEDBACK_REFRESH", "REQUEST_READONLY_REPORT_REBUILD",
    "REQUEST_ALERT_TEST_DRY_RUN", "REQUEST_EVIDENCE_REFRESH_DRY_RUN",
    "REQUEST_READINESS_RECHECK_DRY_RUN", "REQUEST_DECISION_TRACE_EXPORT_DRY_RUN",
)
N3_COMMANDS = (
    "PAPER_KILL_SWITCH", "RESTART_GRID_PAPER", "CHANGE_GRID_PARAMETERS_PAPER",
    "PAUSE_STRATEGY_PAPER", "RESUME_STRATEGY_PAPER", "CLOSE_PAPER_SIMULATION",
    "REQUEST_RISK_REEVALUATION_DRY_RUN", "REQUEST_DATASET_AUDIT_DRY_RUN",
    "REQUEST_OCR_STAGING_AUDIT_DRY_RUN",
)
N4_COMMANDS = (
    "LIVE_ORDER", "MARKET_SELL_ALL_REAL", "SNIPER_REAL", "CANCEL_ALL_LIVE_ORDERS",
    "LIQUIDATE_REAL_INVENTORY", "CHANGE_LIVE_RISK", "ENABLE_LIVE_TRADING",
    "ENABLE_PRIVATE_READ_REAL", "PROMOTE_MODEL_TO_PRODUCTION", "AUTO_INCREASE_CAPITAL",
    "RELEASE_REAL_SAFETY_ORDER", "DISABLE_RISK_MANAGER", "OVERRIDE_KILL_SWITCH_REAL",
    "SEND_REAL_NOTIFICATION_WITH_TOKEN", "WRITE_EXCHANGE_CREDENTIALS",
    "EXECUTE_OCR_IMPORT_OFFICIAL", "WRITE_TRADES_MASTER",
    "PROMOTE_QUALITY_GATED_DATASET", "CLEAN_AI_SHADOW_SQLITE",
    "REBUILD_TRAINING_DATASET_OFFICIAL", "RUN_LIVE_MONTE_CARLO_GATE_OVERRIDE",
    "FORCE_READINESS_APPROVAL", "ENABLE_CANARY_RELEASE", "ENABLE_LIVE_RELEASE",
)

LEVEL_DEFAULTS = {
    DashboardCommandLevel.N1_LOCAL_INFO: (
        DashboardCommandRisk.LOW, DashboardCommandSideEffect.NONE, True, True, False,
    ),
    DashboardCommandLevel.N2_DRY_RUN_STUB: (
        DashboardCommandRisk.MEDIUM, DashboardCommandSideEffect.WOULD_REQUEST_REFRESH,
        True, True, False,
    ),
    DashboardCommandLevel.N3_DRY_RUN_STUB_SENSITIVE: (
        DashboardCommandRisk.HIGH, DashboardCommandSideEffect.WOULD_REQUEST_PAPER_ACTION,
        True, True, False,
    ),
    DashboardCommandLevel.N4_HARD_BLOCKED: (
        DashboardCommandRisk.CRITICAL, DashboardCommandSideEffect.WOULD_REQUEST_LIVE_ACTION,
        False, False, True,
    ),
}
