from __future__ import annotations

import importlib.util
import json
from pathlib import Path


def module_exists(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def main() -> None:
    required_modules = ["pandas", "sqlalchemy"]
    missing_modules = [module for module in required_modules if not module_exists(module)]

    paths = {
        "signals": Path("data/freqtrade_signals.json"),
        "strategy": Path("freqtrade/user_data/strategies/SmartCryptoSignalStrategy.py"),
        "freqtrade_config": Path("freqtrade/user_data/config.paper.json"),
        "freqtrade_db": Path("freqtrade/user_data/tradesv3.paper.sqlite"),
        "data_dir": Path("data"),
    }

    report = {
        "status": "ok" if not missing_modules else "error",
        "missing_modules": missing_modules,
        "paths": {name: {"path": str(path), "exists": path.exists()} for name, path in paths.items()},
        "notes": [
            "freqtrade_db may be created after freqtrade starts",
            "signals file can be generated by RUN_PHASE9_GENERATE_TEST_SIGNAL.ps1",
        ],
    }

    Path("data/reports").mkdir(parents=True, exist_ok=True)
    Path("data/reports/phase9_preflight_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(json.dumps(report, ensure_ascii=False, indent=2))

    if missing_modules:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
