from __future__ import annotations

from collections.abc import Iterable

from smartcrypto.ops.dashboard_snapshots.contracts import (
    DashboardPageId,
    DashboardSourceContract,
    SourceKind,
)


DASHBOARD_SNAPSHOT_FILENAMES = {
    DashboardPageId.infrastructure: "dashboard_infrastructure_snapshot.json",
    DashboardPageId.portfolio_risk: "dashboard_portfolio_risk_snapshot.json",
    DashboardPageId.grid_monitor: "dashboard_grid_monitor_snapshot.json",
    DashboardPageId.opportunity_scanner: "dashboard_opportunity_scanner_snapshot.json",
    DashboardPageId.ai_governance: "dashboard_ai_governance_snapshot.json",
    DashboardPageId.active_controls: "dashboard_active_controls_snapshot.json",
    DashboardPageId.quantitative_reports: "dashboard_quantitative_reports_snapshot.json",
    DashboardPageId.alerts_messaging: "dashboard_alerts_messaging_snapshot.json",
}

GLOBAL_STATUS_SNAPSHOT_FILENAME = "dashboard_global_status_snapshot.json"
SNAPSHOT_BUILD_SUMMARY_FILENAME = "dashboard_snapshot_build_summary.json"


def _source(
    page_id: DashboardPageId,
    path: str,
    source_kind: SourceKind = SourceKind.OPTIONAL_EXISTING_SOURCE,
    description: str = "",
) -> DashboardSourceContract:
    return DashboardSourceContract(page_id, path, source_kind, description)


def _generated(page_id: DashboardPageId) -> DashboardSourceContract:
    filename = DASHBOARD_SNAPSHOT_FILENAMES[page_id]
    return _source(
        page_id,
        f"data/reports/{filename}",
        SourceKind.GENERATED_BY_THIS_BRANCH,
        "Read-only dashboard snapshot generated by the dashboard snapshot family.",
    )


SOURCE_CATALOG: dict[DashboardPageId, tuple[DashboardSourceContract, ...]] = {
    DashboardPageId.infrastructure: (
        _source(DashboardPageId.infrastructure, "data/reports/system_healthcheck_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/market_data_health_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/market_data_health_runtime_sources_report.json"),
        _source(DashboardPageId.infrastructure, "data/reports/critical_alerting_report.json"),
        _source(DashboardPageId.infrastructure, "data/alerts/alert_outbox.jsonl"),
        _source(DashboardPageId.infrastructure, "data/reports/redis_health_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/rate_limit_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/websocket_health_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/exchange_public_latency_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.infrastructure, "data/reports/latency_timeseries.parquet", SourceKind.FUTURE_SOURCE),
        _generated(DashboardPageId.infrastructure),
    ),
    DashboardPageId.portfolio_risk: (
        _source(DashboardPageId.portfolio_risk, "data/reports/state_reconciliation_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.portfolio_risk, "data/reports/order_intent_capital_ledger_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.portfolio_risk, "data/reports/risk_recovery_mode_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.portfolio_risk, "data/reports/critical_alerting_report.json"),
        _source(DashboardPageId.portfolio_risk, "data/runtime/runtime_safety_audit_config.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.portfolio_risk, "data/runtime/kill_switch.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.portfolio_risk, "data/evidence/phase14_*/freqtrade_paper_trades_raw.parquet"),
        _source(DashboardPageId.portfolio_risk, "data/evidence/phase14_*/freqtrade_paper_closed_smartcrypto.csv"),
        _source(DashboardPageId.portfolio_risk, "data/evidence/phase14_*/reports/phase14_open_positions_report.json"),
        _source(DashboardPageId.portfolio_risk, "data/evidence/phase14_*/reports/phase14_closed_feedback_report.json"),
        _source(DashboardPageId.portfolio_risk, "data/reports/paper_financial_performance_metrics_report.json"),
        _source(DashboardPageId.portfolio_risk, "data/reports/financial_event_log.jsonl"),
        _generated(DashboardPageId.portfolio_risk),
    ),
    DashboardPageId.grid_monitor: (
        _source(DashboardPageId.grid_monitor, "data/freqtrade_signals.json"),
        _source(DashboardPageId.grid_monitor, "data/ai/model_decisions.jsonl"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase13_*/active_freqtrade_signals.json"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase13_*/freqtrade_signals.json"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase14_*/freqtrade_paper_trades_raw.parquet"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase14_*/freqtrade_paper_closed_smartcrypto.csv"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase14_*/reports/phase14_open_positions_report.json"),
        _source(DashboardPageId.grid_monitor, "data/evidence/phase14_*/reports/phase14_closed_feedback_report.json"),
        _source(DashboardPageId.grid_monitor, "data/reports/market_data_health_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.grid_monitor, "data/reports/market_data_health_runtime_sources_report.json"),
        _source(DashboardPageId.grid_monitor, "data/reports/order_intent_capital_ledger_audit_report.json"),
        _source(DashboardPageId.grid_monitor, "data/reports/financial_event_log.jsonl"),
        _generated(DashboardPageId.grid_monitor),
    ),
    DashboardPageId.opportunity_scanner: (
        _source(DashboardPageId.opportunity_scanner, "data/reports/market_data_health_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.opportunity_scanner, "data/reports/market_data_health_runtime_sources_report.json"),
        _source(DashboardPageId.opportunity_scanner, "data/ai/model_decisions.jsonl"),
        _source(DashboardPageId.opportunity_scanner, "data/reports/critical_alerting_report.json"),
        _source(DashboardPageId.opportunity_scanner, "data/reports/financial_event_log.jsonl"),
        _source(DashboardPageId.opportunity_scanner, "data/alerts/alert_outbox.jsonl"),
        _source(DashboardPageId.opportunity_scanner, "data/reports/opportunity_spread_scanner_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.opportunity_scanner, "data/reports/triangular_arbitrage_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.opportunity_scanner, "data/reports/order_flow_imbalance_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.opportunity_scanner, "data/reports/launch_radar_snapshot.json", SourceKind.FUTURE_SOURCE),
        _generated(DashboardPageId.opportunity_scanner),
    ),
    DashboardPageId.ai_governance: (
        _source(DashboardPageId.ai_governance, "data/ai/model_decisions.jsonl"),
        _source(DashboardPageId.ai_governance, "data/contracts/phase23_feature_contract.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.ai_governance, "data/predictions/latest_qlib_predictions.parquet"),
        _source(DashboardPageId.ai_governance, "data/features/market_features_60d.parquet"),
        _source(DashboardPageId.ai_governance, "data/reports/qlib_fresh_prediction_runner_report.json"),
        _source(DashboardPageId.ai_governance, "data/reports/qlib_market_features_refresh_report.json"),
        _source(DashboardPageId.ai_governance, "data/models/registry/model_registry.json"),
        _source(DashboardPageId.ai_governance, "data/models/registry/active_model.json"),
        _source(DashboardPageId.ai_governance, "data/runtime/ai_shadow_filter_decisions.sqlite"),
        _source(DashboardPageId.ai_governance, "data/reports/ai_shadow_filter_incremental_daily_summary.json"),
        _source(DashboardPageId.ai_governance, "data/reports/ai_shadow_filter_decision_db_audit_summary.json"),
        _source(DashboardPageId.ai_governance, "data/reports/ai_shadow_drift_monitor_report.json"),
        _source(DashboardPageId.ai_governance, "data/reports/ai_shadow_outcome_attribution_report.json"),
        _source(DashboardPageId.ai_governance, "data/reports/event_driven_backtest_report.json"),
        _source(DashboardPageId.ai_governance, "data/reports/monte_carlo_risk_simulation_report.json"),
        _source(DashboardPageId.ai_governance, "data/reports/financial_event_log.jsonl"),
        _source(DashboardPageId.ai_governance, "data/alerts/alert_outbox.jsonl"),
        _generated(DashboardPageId.ai_governance),
    ),
    DashboardPageId.active_controls: (
        _source(DashboardPageId.active_controls, "data/runtime/runtime_safety_audit_config.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.active_controls, "data/runtime/kill_switch.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.active_controls, "data/alerts/alert_outbox.jsonl"),
        _source(DashboardPageId.active_controls, "data/reports/risk_recovery_mode_audit_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.active_controls, "data/reports/state_reconciliation_audit_report.json"),
        _source(DashboardPageId.active_controls, "data/reports/order_intent_capital_ledger_audit_report.json"),
        _source(DashboardPageId.active_controls, "data/reports/critical_alerting_report.json"),
        _source(DashboardPageId.active_controls, "data/reports/runtime_evidence_refresh_report.json"),
        _source(DashboardPageId.active_controls, "data/reports/runtime_evidence_pack_v2.json"),
        _source(DashboardPageId.active_controls, "data/reports/readiness_snapshot_v2.json"),
        _source(DashboardPageId.active_controls, "data/reports/paper_shadow_soak_gap_accounting_report.json"),
        _source(DashboardPageId.active_controls, "data/reports/dashboard_command_audit_log.jsonl", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.active_controls, "data/reports/dashboard_command_status_snapshot.json", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.active_controls, "data/reports/dashboard_command_policy_snapshot.json", SourceKind.FUTURE_SOURCE),
        _generated(DashboardPageId.active_controls),
    ),
    DashboardPageId.quantitative_reports: (
        _source(DashboardPageId.quantitative_reports, "data/reports/paper_financial_performance_metrics_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.quantitative_reports, "data/evidence/phase14_*/freqtrade_paper_closed_smartcrypto.csv"),
        _source(DashboardPageId.quantitative_reports, "data/evidence/phase14_*/freqtrade_paper_trades_raw.parquet"),
        _source(DashboardPageId.quantitative_reports, "data/evidence/phase14_*/reports/phase14_closed_feedback_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/features/trade_enriched.parquet"),
        _source(DashboardPageId.quantitative_reports, "data/features/training_dataset.parquet"),
        _source(DashboardPageId.quantitative_reports, "data/features/training_dataset_quality_gated_binance_1m.parquet"),
        _source(DashboardPageId.quantitative_reports, "data/reports/event_driven_backtest_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/monte_carlo_risk_simulation_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/model_vs_baseline_financial_evaluation_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/sidecar_financial_evaluation_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/normalized_financial_evaluation_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/market_data_health_audit_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/runtime_evidence_pack_v2.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/readiness_snapshot_v2.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/paper_shadow_soak_gap_accounting_report.json"),
        _source(DashboardPageId.quantitative_reports, "data/reports/financial_event_log.jsonl"),
        _generated(DashboardPageId.quantitative_reports),
    ),
    DashboardPageId.alerts_messaging: (
        _source(DashboardPageId.alerts_messaging, "data/alerts/alert_outbox.jsonl"),
        _source(DashboardPageId.alerts_messaging, "data/reports/critical_alerting_report.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.alerts_messaging, "data/reports/financial_event_log.jsonl"),
        _source(DashboardPageId.alerts_messaging, "data/reports/runtime_evidence_refresh_report.json"),
        _source(DashboardPageId.alerts_messaging, "data/reports/system_healthcheck_report.json"),
        _source(DashboardPageId.alerts_messaging, "data/reports/market_data_health_audit_report.json"),
        _source(DashboardPageId.alerts_messaging, "data/reports/state_reconciliation_audit_report.json"),
        _source(DashboardPageId.alerts_messaging, "data/reports/risk_recovery_mode_audit_report.json"),
        _source(DashboardPageId.alerts_messaging, "data/runtime/kill_switch.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.alerts_messaging, "data/runtime/runtime_safety_audit_config.json", SourceKind.REQUIRED_EXISTING_SOURCE),
        _source(DashboardPageId.alerts_messaging, "data/alerts/dead_letter_queue.jsonl", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.alerts_messaging, "data/reports/notification_delivery_history.jsonl", SourceKind.FUTURE_SOURCE),
        _source(DashboardPageId.alerts_messaging, "data/reports/notification_dispatcher_report.json", SourceKind.FUTURE_SOURCE),
        _generated(DashboardPageId.alerts_messaging),
    ),
}


def sources_for_page(page_id: DashboardPageId | str) -> tuple[DashboardSourceContract, ...]:
    page = page_id if isinstance(page_id, DashboardPageId) else DashboardPageId(page_id)
    return SOURCE_CATALOG[page]


def iter_sources() -> Iterable[DashboardSourceContract]:
    for page_id in DashboardPageId:
        yield from SOURCE_CATALOG[page_id]


def snapshot_path_for_page(page_id: DashboardPageId | str) -> str:
    page = page_id if isinstance(page_id, DashboardPageId) else DashboardPageId(page_id)
    return f"data/reports/{DASHBOARD_SNAPSHOT_FILENAMES[page]}"
